[commands.swipe.three]
left_up = ""
right_up = ""
up = "xdotool key ctrl+F10"
left_down = ""
right_down = ""
down = ""
left = "qdbus org.kde.KWin /KWin previousDesktop"
right = "qdbus org.kde.KWin /KWin nextDesktop"

[commands.swipe.four]
left_up = ""
right_up = ""
up = ""
left_down = ""
right_down = ""
down = ""
left = ""
right = ""
